"""
Django settings for hello_django project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from django.core.urlresolvers import reverse_lazy,reverse
LOGIN_REDIRECT_URL = reverse_lazy('account:home')  #指定成功登陆后的跳转地址
LOGIN_URL = reverse_lazy('account:login')          #指定登陆的地址
LOGOUT_URL = reverse_lazy('account:logout')        #指定登陆退出后的跳转地址
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=s-vp362y067f3a67xl$au9t-uv8@6g6k1#hslin&!nqb_5tiu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = ['www.liuyu.ca','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'account',       #用户认证应用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'hello',        #图书核心展示
    'star_ratings',  #商品评分
    'bootstrap3',    #bootstrap3
    'social_django', #社交认证
    'cart',
    'paypal.standard.ipn',  #支付程序
    'order',
    'payment',
    'taggit',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',   # 社交认证  注意中间件加载的顺序
]

ROOT_URLCONF = 'hello_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'cart.context_processors.cart',      #context_processors 提供上下文的全局变量 一次定义在所有的模板文件中生效
            ],
        },
    },
]

WSGI_APPLICATION = 'hello_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    'social_core.backends.google.GoogleOpenId',  # for Google authentication
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.weibo.WeiboOAuth2',
   'django.contrib.auth.backends.ModelBackend',
)

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_TZ=True
TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SOCIAL_AUTH_GITHUB_KEY ='04df96b2e3abda5a9f5f'
SOCIAL_AUTH_GITHUB_SECRET = '8a15016c2ba041b0d715f84f97abd0b9652ba2a5'
SOCIAL_AUTH_TWITTER_KEY = 	'A9rO4vavVtwR6RVFrZu85uEMI'
SOCIAL_AUTH_TWITTER_SECRET = 'qoAexb1FlNUnAsH5ybslsDZHe6oq48BBOcbaoYK9x08opAx2g3'
SOCIAL_AUTH_FACEBOOK_KEY = '1686428098072704'
SOCIAL_AUTH_FACEBOOK_SECRET = '8e1379d0a51efc914a77e6436cd4a130'
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '669536186993-qk14vhe19bvfl2bsnfb93r8v1oikvv9u.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'GzLlJR3dXLJlkxW_ZMgQ15VS'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '669536186993-u6tue504naq5gojp1p17f0g9cod8m510.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'G2fP9zVz2WJyCIs6ptLobMrU'

SOCIAL_AUTH_WEIBO_KEY = '2766176293'   #΢²©
SOCIAL_AUTH_WEIBO_SECRET = 'b0deae4adefec67ee0d2033e72d94108'  #΢²©
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
CART_SESSION_ID = 'cart'   # CART_SESSION_ID常量
STATIC_ROOT=os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'liuyuwebadm@gmail.com'
EMAIL_HOST_PASSWORD = 'Jess1211'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# LOGIN_URL = reverse('account:login')
# LOGOUT_URL = reverse('account:logout')
# LOGIN_REDIRECT_URL = reverse('account:home')

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')


#django-paypal settings
#PAYPAL_RECEIVER_EMAIL='ericlew1973@gmail.com'
PAYPAL_RECEIVER_EMAIL='ericlew1973-facilitator@gmail.com'
PAYPAL_TEST=True

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
# HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'